### ISSUE TITLE
TypeError: Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by Micu22** [satorumurmur/bibi#100]
I have a problem on some epubs: Bibi reader opens, but an error is shown: TypeError: Cannot read property 'childNodes' of undefined.
What can I do?

**Comment by Micu22** [comment]
I apparently didn't fully understand this. So after trying some rewrite rules in htaccess I made it work on the webserwer.
I have another problem on some epubs: Bibi reader opens, but an error is shown: TypeError: Cannot read property 'childNodes' of undefined.
What can I do?

**Comment by satorumurmur** [comment]
@Micu22 
Can you show me the EPUB file or the URL of published it with Bibi?

**Comment by Micu22** [comment]
Here is one that doesn't open on my system and give a: TypeError: Cannot read property 'childNodes' of undefined.
[Killing yourself to live  85% of a true story.zip](https://github.com/satorumurmur/bibi/files/5604765/Killing.yourself.to.live.85.of.a.true.story.zip)

**Comment by satorumurmur** [comment]
Each content of this EPUB file seemes to be encrypted, probably for protection. (Adobe DRMed EPUB ???)
Bibi (and probably many other general-purpose/free-software viewers) can't open DRMed EPUB.

**Comment by Micu22** [comment]
Okay this is probable. It isn't a problem for me, what I need opens properly, thanks.
