### ISSUE TITLE
Path resolving error

### ISSUE THREAD

**Issue by KitaitiMakoto** [satorumurmur/bibi#17]
BiB/i doesn't seem able to parse svg-entry-sample.epub file linked from http://blog.cas-ub.com/?p=1094 correctly.
It requests /bib/i/styles/style.css but it doesn't exist. It should be a request to OEBPS/styles/style.css.

**Comment by satorumurmur** [comment]
While opening zipped EPUB, when encode and embed the content of a file in another file as data-URI, BiB/i hadn't distinguish between that the file is not in zipped archive and that the content of the file is "" (blank).

Now it's fixed. Thank you!

**Comment by KitaitiMakoto** [comment]
I confirmed the issue fixed. Thanks.
