### ISSUE TITLE
Probem with unzipped epub

### ISSUE THREAD

**Issue by howsiyu** [satorumurmur/bibi#22]
This works:
http://mywebsite/bibi/bib/i/?book=a.epub

This doesn't.
unzip a.epub -d a
http://mywebsite/bibi/bib/i?book=a

**Comment by satorumurmur** [comment]
@howsiyu
Thank you for your reporting.
But It seems to be working, in my development environment.
Can I ask you to send the a.epub to me? I will test with it.

**Comment by howsiyu** [comment]
I have sent it to your personal gmail as shown in your github profile.

**Comment by satorumurmur** [comment]
I'm sorry my reply is so late. I'll test your EPUB in a few days.

**Comment by satorumurmur** [comment]
I'm very sorry for my laziness.
Please try the latest version - http://bibi.epub.link/my/name/is/bibi-0.999.4.zip
