### ISSUE TITLE
the demo can't read *.epub file by URL mode

### ISSUE THREAD

**Issue by sywlb** [satorumurmur/bibi#23]
I have uploaded the aaa.epub to bookshelf
input the following linkadress:
http://www.XXX.com/bibi/bib/i/?book=9787536455382.epub
but it doesn't works(win7\win2003\win2008)

When I test the demo site on winxp,it works well

I don't know why,please help me

**Comment by satorumurmur** [comment]
Are the web browsers you tested IEs?
I found that IEs (including IE11) are not able to process the zipped EPUB file because of IE's policy.
I'm sorry.
