### ISSUE TITLE
EPUB CFI doesn't work when text node is specified

### ISSUE THREAD

**Issue by KitaitiMakoto** [satorumurmur/bibi#25]
Moving to page specified by EPUB CFI is unique and great feature but there seems an issue. When you specify text node using EPUB CFI like `#epubcfi(/6/14!/4/46/1)`, BiB/i start with the first page instead of the page `itemref` of `14` refers.

Not to move to the text node but the begining of XHTML page including the node is okay. But not to move anywhere and showing error "Uncaught TypeError: Cannot read property 'childNodes' of null" in console is problem.

My environment:
- Ubuntu 15.10
- Chromium 45.0
- Revision 6b5d0d1

**Comment by satorumurmur** [comment]
（放置のママだけどゴメン５年前なのでひとまず閉じる……）
