### ISSUE TITLE
Does BiBi reader support bookmarks?

### ISSUE THREAD

**Issue by bdfinlayson** [satorumurmur/bibi#26]
Does BiBi support the concept of bookmarks (i.e. track a reader's reading position in a document)? I have a use case where readers might read half-way through a document, for example, and then need to return to where they left off at a later date.

**Comment by satorumurmur** [comment]
Thank you for your trying and reporting.
Now you can return to where you left off at last time. (Using a Cookie)
And the bookmarking feature may be added in the next version with EPUBCFI. Please wait.

* v0.999.4 - http://bibi.epub.link/my/name/is/bibi-0.999.4.zip
