### ISSUE TITLE
Cannot read book from extracted files

### ISSUE THREAD

**Issue by KitaitiMakoto** [satorumurmur/bibi#28]
@satorumurmur 
Hi,

I found the case you cannot read book from extracted files. Steps to reproduce the issue is:

1. Prepare EPUB file, now accessible_epub_3.epub from https://drive.google.com/folderview?id=0B9g8D2Y-6aPLflZXSGVlYlBUUUdZZ1VURlZSVndraDNGMkhReXVoem1MdXIwYUNaeVhWU0E&usp=drive_web&tid=0B9g8D2Y-6aPLflIyZE50Um50cG5BNkZSQ2NqcVhtUlZJSGRoVWhla3ktZ2JQdDJjdFNyZlk
2. Download BiB/i: `wget http://bibi.epub.link/my/name/is/bibi-0.998.3.zip`
3. Unzip BiB/i: `unzip bibi-0.998.3.zip`
4. Unzip the EPUB book: `unzip accessible_epub_3.epub -d bibi-0.998.3/bib/bookshelf/accessible_epub_3.epub`
5. Run web server: `ruby -run -e httpd -- . -p 8000`
6. visit http://localhost:8000/bibi-0.998.3/bib/i/index.html?book=accessible_epub_3.epub 

then, spinner spins forever. http://localhost:8000/bibi-0.998.3/bib/i/index.html?book=accessible_epub_3.epub/ (trailing slash)also doesn't work.

Is that a bug? or expected behavior?

Thanks.

**Comment by satorumurmur** [comment]
I've solved it.
You can use both folder and zipped file which named as "*.epub" now.
Thanks.
