### ISSUE TITLE
Audio playback on embedded video EPUB3

### ISSUE THREAD

**Issue by askadrian** [satorumurmur/bibi#33]
I notice when you  drag the ebook locally to the bib "upload" interface that it will play audio but when you embedded it into the library at the back of the site it will mute or not allow the audio to play.

is there a suggested fix or work around?

**Comment by askadrian** [comment]
this is a problem that also is an issue for video playback

**Comment by satorumurmur** [comment]
I'm afraid that It may be problem of setting of web server or HTTP header from it. But it also may be some bugs in BiB/i.

In development for the next version, I'll try to enhance to support audio/video more for Text to Speech or Media Overlays.

Please wait for the future version. Thanks.
