### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by Jajjy** [satorumurmur/bibi#38]
I`m trying adding a "Download" button, in the drop down menu, but looks like a can`t (I`m not so expert in JS).
Is there a chance to implement it?

I also tried doing it in a separate page, putting "index.html" inside a iframe, but this won-t work either, since the index won`t load the epub.

any suggestion?

**Comment by satorumurmur** [comment]
I'll add the download feature in `Share` extension or another new extension.
(when the EPUB that BiB/i opened is zipped *.epub, users can use `download`.)
Please wait for feature version.
