### ISSUE TITLE
Links on navigation pane work improperly on mobile devices

### ISSUE THREAD

**Issue by gitgary** [satorumurmur/bibi#39]
I've found that choosing items from the navigation pane work very infrequently on iOS and Android.  After much investigation, it seems to be because the 'click' event is not being fired most of the time.  I was able to fix it locally with the following code fragment below:

L.postprocessItem.coordinateLinkages.setJump = function(A) {
	eventName = O.Mobile ? "touchstart" : "click"

    A.addEventListener(eventName, function(Eve) {

**Comment by pravid** [comment]
This solution not working for me.

**Comment by satorumurmur** [comment]
@gitgary @pravid Thanks for your reporting and proposition. I'll try fixing based on your opinions.

**Comment by satorumurmur** [comment]
@gitgary @pravid
It's fixed. I'm sorry to have kept you waiting.

### detail:
Commt: 03d9415cbae1b21e49c912101ad5c2945713652b
Removed an unnecessary event listener which prevents to call other listeners.
(I can't come up with that why I added such a thing....)
