### ISSUE TITLE
Bug with encoding special characters

### ISSUE THREAD

**Issue by steplero** [satorumurmur/bibi#4]
I have problems with some french special characters in the html content like 'é' rendered with a '頻' or 'à' rendered with a ''࠻... 
Html is encoded in utf-8.
This problem does not occur all the time but only with some words or maybe some strings of characters. I don't understand why…
Have you any idea ?
Thanx.

**Comment by satorumurmur** [comment]
Please try the latest version again.

**Comment by satorumurmur** [comment]
The latest version is here.
v0.999.4 - http://bibi.epub.link/my/name/is/bibi-0.999.4.zip
