### ISSUE TITLE
XML support

### ISSUE THREAD

**Issue by pravid** [satorumurmur/bibi#40]
Does this plugin support ePubs with XML content? I have an ePub which has XML files in it. It shows the TOC correctly but pages are not loaded. This ePub opens fine with normal ePub reader but not with this one.

**Comment by satorumurmur** [comment]
@pravid
Thanks for testing and reporting.
May I ask you to send me the EPUB file?
I'll try to support it and EPUBs with XMLs like it.

**Comment by pravid** [comment]
I'm not able to upload zip file. It is giving error as 'no support'.

**Comment by satorumurmur** [comment]
I'm so sorry to leave you not replying.

Bibi supported XML content like your sample EPUB, in the version released in 2017 or 2018.
