### ISSUE TITLE
without dragging and dropping files 

### ISSUE THREAD

**Issue by MrXCQ** [satorumurmur/bibi#68]
How to get local ePub files without dragging and dropping files to upload

**Comment by KitaitiMakoto** [comment]
@MrXCQ Hi,
You can do it by just tapping(or clicking) a window:
[![Image from Gyazo](https://i.gyazo.com/0b0d8fd372850fa66f6ceb15034e491d.gif)](https://gyazo.com/0b0d8fd372850fa66f6ceb15034e491d)

**Comment by satorumurmur** [comment]
( thanks @KitaitiMakoto )
