### ISSUE TITLE
Is there any way to start ebook from specific page

### ISSUE THREAD

**Issue by ahmettkartal** [satorumurmur/bibi#71]
I want users to start reading from the page where they left off before. Is there any way for this issue?

**Comment by brkdmn35** [comment]
Hi Ahmet, I tried to contact owner of project but he did not answer me.
Then after hours of work, i started to understand code. It is really complicated.

If you can see activate part on bibi.js, you can define your first page as,
R.Current.Page.PageIndex = {your first page];
E.dispatch("bibi:commands:move-by",1); \\this part take to destination page

I hope owner will update documentation for users in future :(

**Comment by ahmettkrtl** [comment]
> Hi Ahmet, I tried to contact owner of project but he did not answer me.
> Then after hours of work, i started to understand code. It is really complicated.
> 
> If you can see activate part on bibi.js, you can define your first page as,
> R.Current.Page.PageIndex = {your first page];
> E.dispatch("bibi:commands:move-by",1); \this part take to destination page
> 
> I hope owner will update documentation for users in future :(

Thank you so much Burak it works. 🎊 🎊

**Comment by satorumurmur** [comment]
@ahmettkartal @brkdmn35 
Thanks for using Bibi. I'm sorry for the lazy response.

In the latest release (v1.2.0), you can use the `p` identifier in URL to specify the point in the book, like these:
* https://bibi.epub.link/my/name/is/bibi/?book=idpf/samples/WCAG#p=2 (2nd file in spine)
* https://bibi.epub.link/my/name/is/bibi/?book=idpf/samples/WCAG&p=2 (same as the above)
* https://bibi.epub.link/my/name/is/bibi/?book=idpf/samples/WCAG#p=2.1.6.8.9.3 (2nd file's body element's 1st child element's 6th child element's...) = picture of a goat. 
* https://bibi.epub.link/my/name/is/bibi/?book=idpf/samples/WCAG#p=2.1.6.8.9.3 (same as the above)

In the next some releases, I will make it possible to get the `2.1.6.8.9.3` of double-clicked element.

In the current version, you can get the `p` identifier value of the element near the head of the current view by `I.PageObserver.getP()` or `I.PageObserver.getP({ TagNames: ['figure', 'p'] })` or so on, but this is quite rough.

On another way, you can also use the `iipp` identifier which existing as the system function from before, like these:
* https://bibi.epub.link/my/name/is/bibi/?book=idpf/samples/WCAG#iipp=1.66 (66% of R.Items[1])
* https://bibi.epub.link/my/name/is/bibi/?book=idpf/samples/WCAG&iipp=1.66 (same as the above)

But point specified by `iipp` is quite "about" and different on each user's display size.
