### ISSUE TITLE
can not open file with error "file not included "

### ISSUE THREAD

**Issue by librix** [satorumurmur/bibi#80]
![image](https://user-images.githubusercontent.com/10742127/78756685-cafb6e80-79ad-11ea-9978-826378aad3f0.png)

chrome set as:
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-web-security --allow-file-access-from-files --disable-plugins

epub has its own font.

**Comment by satorumurmur** [comment]
Could you send me the EPUB file?

**Comment by satorumurmur** [comment]
Please try latest version. - https://github.com/satorumurmur/bibi/releases/tag/v1.2.0
If your trouble is not solved on the new version, please report it again. @librix
