### ISSUE TITLE
Bibi does not send the cookies

### ISSUE THREAD

**Issue by a-yasui** [satorumurmur/bibi#81]
Bibi v0.999.9-r8 から Bibi v1.1.1 にバージョンアップをしたところ、 Cookie を投げなくなって少し困ってます。

アドバイスをいただけたら幸いです。

# 現象

Bibi v0.999.9-r8 では Epub を取得する時に Cookie を投げていましたが、Bibi v1.1.1 で投げなくなったため、認証が必要なEPubコンテンツの取得ができなくなった。

Epubコンテンツは同一ホストにあるので、default.js にある `trustworthy-origins` は `[]` にしています。

開発者ツールのスクリーンショットを添付します。（都合上、クッキーの内容とホスト名は伏せています。）

## v0.999.9-r8 

![bibi v0.999.9-r8](https://user-images.githubusercontent.com/94186/82234797-d0fd4b80-996c-11ea-9bd3-13f0c5bc74ba.png)

## v1.1.1

![bibi v1.1.1](https://user-images.githubusercontent.com/94186/82234852-e5414880-996c-11ea-921d-d1ecc5dd1ce8.png)

**Comment by a-yasui** [comment]
あー…ごめんなさい。 httpOnly が元ページの読み込み時に投げていました。

すっかり失念していました。

**Comment by satorumurmur** [comment]
v1.0.0 より古い Bibi は設定の保存と最終表示位置の保存のために Cookie を使用していましたが、v1.0.0 以降では localStorage に移行し、Cookie を使用しなくなりました。さらにその際、リクエストの肥大化を避けるべく[旧バージョンの Cookie を消す処理](https://github.com/satorumurmur/bibi/blob/92df70ef098ed10ea02ddcdabdc557689987baa1/__src/bibi/resources/scripts/bibi.heart.js#L5800)を入れてあったりもします。

もし Bibi 自身が記録していた Cookie に依存する実装があった場合は、Cookie を利用しなくなったり削除するようになったりしたことが問題になってしまったかもしれません（すみません）。が、根本的には、認証に関わるようなクリティカルな目的には、独自の実装をしていただくほうが一般論としても良いのではないかと考えます（こと Bibi の Cookie に関しては、Bibi 側としてはあくまでもテンポラリデータを保持するためだけの Cookie で、また、旧来形式で再度 Cookie を使い始める予定もないため、これに頼ってしまうのは弱いように思われます）。

ただ、（おそらく最後にいただいているコメントもこのことかと思いますが、）Bibi が Cookie を投げなくなっているわけではありません。したがいまして、独自実装で Cookie をご利用になること自体は可能だと思います。

　＊

なお、上でリンクさせた旧バージョンの Cookie を消す処理の１行についてはそろそろ消そうと思っていますので、お手元のバージョンからもあらかじめ削除して次のバージョンをお待ちいただいて問題ありません。ただ、やはり認証に関わる部分は独自に実装していただくようにお願いします（ご依頼があればエクステンション形式での機能追加など、協力させていただきます）。
