### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Marcus-Lacia** [satorumurmur/bibi#82]
my website is install and use bibi epub
Bug :if you have many epub to view the ProgressBar will fixed;
such as 
i view a 001book.epub at page6，and then i open 002book.epub，the progressBar will show the page6 instead of page1

**Comment by satorumurmur** [comment]
Could you send me the URL(s)?

**Comment by Marcus-Lacia** [comment]
https://view.alicegearaegis.club/bibi/?book=01.epub

**Comment by Marcus-Lacia** [comment]
i send url to your gmail

**Comment by satorumurmur** [comment]
Every EPUB publication must have dc:identifier in OPF file, and its value should be defferent from every other EPUBs.

Your 01.epub and 02.epub have the same value in dc:identifier, so they are considered the same EPUB by Bibi.

Therefore, modify each EPUB to have a different identifier. That should solve it.

**Comment by satorumurmur** [comment]
// Your EPUB is comic book, but it is made as reflowable.
// I recommend you to make as pre-paginated (fixed-layout) books.
