### ISSUE TITLE
Very slow loading problem

### ISSUE THREAD

**Issue by hrvoj3e** [satorumurmur/bibi#85]
Could you please check [this file](https://drive.google.com/file/d/1Ds7tpqpVkjT1vQOGgfu_Ly7s0KmLZVzk/view)?
Using epub.js it loads fast but bibi loads it 43 seconds (browser tab freezes in Chrome).

Bibi makes 4032 requests and loads 46.7 MiB of blobs.
Epub file is only 4.8 MiB and unpacked 6.2 MiB.

![screenshot-newtab-2020 06 15-09_06_04](https://user-images.githubusercontent.com/4988133/84627684-a0ff8480-aee7-11ea-9cc0-1479dfc87837.png)

**Comment by satorumurmur** [comment]
Thanks for trying and reporting.

Your EPUB consists of 1309 XHTMLs and all of them are reflowable content.

I'm so sorry but Bibi on now is not good at opening this kind of book which contains hundreds of items to be shown reflowable. (It's the problem around the number of the items, not the total size.)

In the future, I want Bibi able to load content asynchronously not only for pre-paginated/fixed-layout books but also for reflowable books. But for now, Bibi can't.

**Comment by hrvoj3e** [comment]
Too bad. Nice viewer, though.

Client has different epubs and we are trying to show then in a web viewer.

Can we load this kind of epub faster with Bibi? 
 - one page only
 - forced fixed layout
Or something like that?

**Comment by satorumurmur** [comment]
@hrvoj3e  Thanks & sorry.

--------

> Can we load this kind of epub faster with Bibi?
> (...)

Take a look at these samples please.

* Fast (reflowable, 3 items) - https://bibi.epub.link/my/name/is/bibi/?book=idpf/samples/WCAG
* Slow but can (reflowable, 142 items) - https://bibi.epub.link/my/name/is/bibi/?book=idpf/samples/moby-dick
* Very Fast (fixed, 9 items) - https://bibi.epub.link/my/name/is/bibi/?book=idpf/samples/page-blanche-bitmaps-in-spine

If it's a fixed-layout book, Bibi will open quickly, even if it contains 300 or 400 or more items.
