### ISSUE TITLE
ePUB File created using MacOS Pages app shows as blank

### ISSUE THREAD

**Issue by kenanchristian** [satorumurmur/bibi#86]
I was using iBooks Author before and the reader works fine. But the iBooks Author app will be discontinued on July 1, 2020, and apple encourages the user to use the Pages app.

I tried creating the epub using one of the Pages app templates and tried reading it using the reader and it only shows a blank page. The generated EPUB file can be found [here](https://drive.google.com/file/d/1HR403wWd7qR9Ld4xttkIR-2JePaMSSt0/view?usp=sharing)

After some further investigation, the content of `.xhtml` the file contains a self-closing script tag that is valid in XHTML but I think that causes the problem because when I updated it to a normal script tag the page loads just fine.

**Comment by satorumurmur** [comment]
Exactly what you thought.

This issue has been fixed in the develop branch. However, other issues need to be resolved, so please wait 1-2 week(s) before merging it to master and releasing as the next version.

**Comment by kenanchristian** [comment]
Oh okay, that's good to hear. Thank you for the update, I'll close this issue and wait for the next release :)

**Comment by satorumurmur** [comment]
@kenanchristian Please try the latest version released just now. Thanks.
