### ISSUE TITLE
The EPUB's are getting cropped 

### ISSUE THREAD

**Issue by rahak** [satorumurmur/bibi#88]
I installed bibi in my web server. When I tried opening Epubs some parts are getting cropped. 
When I opened it on Apple's ibook. The files are fine.

I have used Epub 3.0 exported from Adobe indesign (fixed layout). My Files are Comics image heavy.

**Comment by rahak** [comment]
Oh! also they are not getting cropped when I zoom out in the browser, But when the browser is showing normal size the files are cropped.

**Comment by satorumurmur** [comment]
Thanks for using Bibi.

Please try the latest version released just now!

**Comment by satorumurmur** [comment]
@kurema Is that resolved by update? If so, I'm relieved. Thanks!

**Comment by kurema** [comment]
???

**Comment by satorumurmur** [comment]
@kurema 申し訳ありません！ メンション間違えました。失礼しました。別件プルリクエストについて、ありがとうございます。

**Comment by satorumurmur** [comment]
@rahak Is that resolved by update? If so, I'm relieved. Thanks!
